version: '3.8'

services:
  app:
    image: tsscrew/dat-service:v1
    ports:
      - "8080:8080"
    networks:
      - dat-network
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dat-network
    restart: always

networks:
  dat-network:
    external: true
